let Foods = [
  {
    id: 1,
    foodImg: "./images/FoodsList/food1.png",
    rateImg1: "./images/person/person9.png",
    rateImg2: "./images/person/person3.png",
    rateImg3: "./images/person/person5.png",
    price: 10,
    rateNum: 4.5,
    name: "Kebab",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
  },

  {
    id: 2,
    foodImg: "./images/FoodsList/food2.png",
    rateImg1: "../images/person/person7.png",
    rateImg2: "../images/person/person2.png",
    rateImg3: "../images/person/person4.png",
    price: 15,
    rateNum: 4.8,
    name: "Chicken Tikka",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
  },

  {
    id: 3,
    foodImg: "./images/FoodsList/food3.png",
    rateImg1: "./images/person/person8.png",
    rateImg2: "./images/person/person1.png",
    rateImg3: "./images/person/person6.png",
    price: 8,
    rateNum: 4.2,
    name: "Desi Chowmein",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
  },

  {
    id: 4,
    foodImg: "./images/FoodsList/food4.png",
    rateImg1: "./images/person/person9.png",
    rateImg2: "./images/person/person3.png",
    rateImg3: "./images/person/person5.png",
    price: 28,
    rateNum: 5.0,
    name: "Chicken Chargha",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
  },
];
let FoodShopData = [
  {
    id: 1,
    foodImg: "./images/shop/food1.png",
    rateImg1: "./images/person/person9.png",
    rateImg2: "./images/person/person3.png",
    rateImg3: "./images/person/person5.png",
    price: 10,
    rateNum: 4.5,
    name: "Kebab",
    title: "lunch",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
  },
  {
    id: 2,
    foodImg: "./images/shop/food2.png",
    rateImg1: "./images/person/person9.png",
    rateImg2: "./images/person/person3.png",
    rateImg3: "./images/person/person5.png",
    price: 10,
    rateNum: 4.5,
    name: "pizza",
    title: "italian",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
  },
  {
    id: 3,
    foodImg: "./images/shop/food3.png",
    rateImg1: "./images/person/person9.png",
    rateImg2: "./images/person/person3.png",
    rateImg3: "./images/person/person5.png",
    price: 10,
    rateNum: 4.5,
    name: "pancake",
    title: "breakfast",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
  },
  {
    id: 4,
    foodImg: "./images/shop/food4.png",
    rateImg1: "./images/person/person9.png",
    rateImg2: "./images/person/person3.png",
    rateImg3: "./images/person/person5.png",
    price: 10,
    rateNum: 4.5,
    name: "kofteh",
    title: "lunch",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
  },
  {
    id: 5,
    foodImg: "./images/shop/food5.png",
    rateImg1: "./images/person/person9.png",
    rateImg2: "./images/person/person3.png",
    rateImg3: "./images/person/person5.png",
    price: 10,
    rateNum: 4.5,
    name: "hamburger",
    title: "lunch",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
  },
  {
    id: 6,
    foodImg: "./images/shop/food6.png",
    rateImg1: "./images/person/person9.png",
    rateImg2: "./images/person/person3.png",
    rateImg3: "./images/person/person5.png",
    price: 10,
    rateNum: 4.5,
    name: "chesseburger",
    title: "lunch",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
  },
  {
    id: 7,
    foodImg: "./images/shop/food7.png",
    rateImg1: "./images/person/person9.png",
    rateImg2: "./images/person/person3.png",
    rateImg3: "./images/person/person5.png",
    price: 10,
    rateNum: 4.5,
    name: "stake",
    title: "dinner",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
  },
  {
    id: 8,
    foodImg: "./images/shop/food8.png",
    rateImg1: "./images/person/person9.png",
    rateImg2: "./images/person/person3.png",
    rateImg3: "./images/person/person5.png",
    price: 10,
    rateNum: 4.5,
    name: "pasta",
    title: "lunch",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
  },
];
let TitleShopData = [
  { id: 1, name: "All", flag: true },
  { id: 2, name: "Breakfast", flag: false },
  { id: 3, name: "Lunch", flag: false },
  { id: 4, name: "Dinner", flag: false },
  { id: 5, name: "Maxican", flag: false },
  { id: 6, name: "Italian", flag: false },
  { id: 7, name: "Desserts", flag: false },
  { id: 8, name: "Drinks", flag: false },
];

let Users = [
  { Id: 1, Name: "milad", Password: 138121, Email: "miiladiighj@gmail.com" },
  { Id: 1, Name: "alireza", Password: 1010, Email: "alireza@gmail.com" },
  { Id: 1, Name: "ehsan", Password: 2020, Email: "ehsan@gmail.com" },
  { Id: 1, Name: "zahra", Password: 3020, Email: "zahra@gmail.com" },
];

export { Users, Foods, FoodShopData, TitleShopData };
